const sportsOptions = {
    FootSports: [
      'Run',
      'Trail Run',
      'Walk',
      'Hike',
      'Virtual Run',
    ],
    CycleSports: [
      'Ride',
      'Mountain Bike Ride',
      'Gravel Bike Ride',
      'E-Bike Ride',
      'E-Mountain Bike Ride',
      'Velomobile',
      'Virtual Ride',
    ],
    WaterSports: [
      'Canoe',
      'Kayak',
      'Kitesurf Session',
      'Row',
      'Stand Up Paddle',
      'Surf',
      'Swim',
      'Windsurf Session',
    ],
    WinterSports: [
    'Ice Skate',
    'Alpine Ski',
    'Backcountry Ski',
      'Nordic Ski',
      'Snowboard',
      'Snowshoe',
    ],
    OtherSports: [
      'Golf',
      'Handcycle',
      'Inline Skate',
      'Rock Climb',
      'Roller Ski',
      'Wheelchair',
      'Crossfit',
      'Elliptical',
      'Sailing',
      'Skateboarding',
      'Soccer',
      'Stair Stepper',
      'Weight Training',
      'Yoga',
      'Workout',
      'Tennis',
      'Pickleball',
      'Racquetball',
      'Squash',
      'Badminton',
      'Table Tennis',
      'HIIT',
      'Pilates',
      'Virtual Row',
    ],
  };
  
  export default sportsOptions;
  